### ISSUE TITLE
trying to fix the applescript issue

### ISSUE THREAD

**Issue by jennynot** [pistolenernie/Spotify4Me#2]
Hi, I love the idea of your app - thanks so much for going to the trouble to code and share it. I noticed you mentioned an applescript issue, and though the control buttons appeared in the notification centre there was no indication of which song was currently playing. I assumed this was the missing functionality you were referring to. 

I patched the plist file as suggested and restarted both Spotify, the app and my computer when these didn't work. This does not seem to have fixed the issue, and actually seems to have broken the app which no longer works to change the track. Do you have any ideas?

**Comment by pistolenernie** [comment]
Hey Jenny,
actually I haven't looked anymore in my code since my last update. Maybe I find at the weekend some time to update the app in regarding the communication between this app and the spotify app and also with respect to the UI design ... I know that it does not look very nice :-D

**Comment by jennynot** [comment]
Hi, 

amazingly quick reply!

don’t worry too much - I actually found an app in the app store that will suffice. It doesn’t have the awesomeness yours does with he notification centre so you still have that niche for sure! But it will do in the mean time ;p

have a lovely day,

Jen

**Comment by pistolenernie** [comment]
If you want one with a notification center, you can try the following one.

https://itunes.apple.com/hk/app/miniplay-notification-center/id936243210?mt=12

I have not tested it, so I can't guarantee anything but maybe that's what you want. ;-)

**Comment by jennynot** [comment]
oh nice, thanks!

**Comment by pistolenernie** [comment]
updated the project with working album covers, hope you like it :-)

**Comment by jennynot** [comment]
ooh thanks I’ll take a look!
