### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by bsealy** [pistolenernie/Spotify4Me#3]
I had one of the versions where album covers didn't work, so I installed the latest version. However, it doesn't work at all anymore. The header shows in Notification Center, but none of the information or controls show.
<img width="317" alt="screen shot 2015-11-15 at 8 37 05 pm" src="https://cloud.githubusercontent.com/assets/15863342/11172635/af6650e4-8bd8-11e5-854f-f5126fb791a2.png">

**Comment by pistolenernie** [comment]
SpotifyMain is running? Spotify itself is running? Have you removed and added the widget again with the 'Edit' option at the bottom of the notification center?
